apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: d2gzeu23u-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/d2gzeu23u-java-springboot-gitops